version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: grafana_postgres
    environment:
      POSTGRES_DB: grafana_db
      POSTGRES_USER: grafana_user
      POSTGRES_PASSWORD: grafana_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - postgres
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: postgres:5432
      GF_DATABASE_NAME: grafana_db
      GF_DATABASE_USER: grafana_user
      GF_DATABASE_PASSWORD: grafana_pass
      GF_DATABASE_SSL_MODE: disable
      GF_INSTALL_PLUGINS: netsage-sankey-panel
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: netsage-sankey-panel
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  grafana_data:

